version : '3'

services : 

  frontend:
    build:
      context: './frontend'
    networks:
      unsecured-network:
        ipv4_address: 172.15.200.3
    ports:
      - 80:80
    links:
      - api

  api: 
    depends_on:
      - db
    networks:
      unsecured-network:
        ipv4_address: 172.15.200.2
    build:
      context: './backendJavascript'
    links:
      - db
    ports:
      - 4000:4000
    restart: always


  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    networks:
      unsecured-network:
        ipv4_address: 172.15.200.1
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./backendSQL/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    networks:
      unsecured-network:
        ipv4_address: 172.15.200.4
    environment:
      ADMINER_DEFAULT_DB_HOST: 172.15.200.1
    ports:
      - 8080:8080

networks:
  unsecured-network:
    ipam:
      driver: default
      config:
        - subnet: 172.15.200.0/16
          ip_range: 172.15.200.0/24